# Configuraci\u00c3\u00b3n de MySQL
# Tambi\u00c3\u00a9n puede usar las variables de entorno DB_URL, DB_USER y DB_PASSWORD.
db.url=jdbc:mysql://localhost:3306/gestion_laboratorios
db.user=root
db.password=RodRO!!121530
